version: '2'

services:
  
  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    extra_hosts:
        - "peer0.org1.example.com:101.200.80.233"
        - "peer1.org1.example.com:123.56.133.49"
        - "orderer.example.com:182.92.112.55"
    environment:
      # for Kafka
      #- CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - ORDERER_GENERAL_ORDERERTYPE=solo
      #- CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka1:9092]
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=orderer.example.com:7050

